### ISSUE TITLE
1.0.4 업데이트 후, 관리비 항목(관리비 납부 제외) 구성요소들이 사라졌습니다.

### ISSUE THREAD

**Issue by HW-YUN** [lunDreame/homeassistant-apti#8]
1.0.2에선 관리비/에너지 항목 모든 구성요소들이 나타났는데, 1.0.3을 거쳐 1.0.4 업데이트를 하니 관리비 항목에서 관리비 납부금액을 제외한 모든 구성요소들이 사용불가로 나타났습니다. 에너지 항목은 이상 없구요.
통합구성요소를 삭제 후 재설치 해도 마찬가지였고, HACS 1.0.2로 롤백 후 1.0.4 재설치 하니 사용불가 요소들 모두 사라지고, 관리비 납부금액 한개만 나타납니다. 에너지 항목 포함 총 7개 구성요소만 나타납니다.

1. 로그북 내용
이 오류는 사용자 통합구성요소에서 발생했습니다.
  로거: custom_components.apti
  소스: custom_components/apti/helper.py:19
  통합구성요소: 아파트아이 (관련 문서, 문제)
  처음 발생: 2024년 10월 21일 오후 9:31:23 (6 발생)
  마지막 로그인: 2024년 10월 24일 오전 9:09:01
  8월분 부과 금액을 찾을 수 없습니다.
  납부할 금액을 찾을 수 없습니다.

2. XHR 첨부파일
[www.apti.co.kr.har.zip](https://github.com/user-attachments/files/17513317/www.apti.co.kr.har.zip)

**Comment by vapury** [comment]
저와 똑같은 문제네요... 아이디로 로그인해도 이렇네여

**Comment by Alegroha** [comment]
저도 동일하네요.

**Comment by lunDreame** [comment]
@vapury 
@Alegroha 
@HW-YUN 
v1.0.5 테스트 부탁드립니다~

**Comment by vapury** [comment]
> @vapury @Alegroha @HW-YUN v1.0.5 테스트 부탁드립니다~

1.0.5  에서 해결됐습니다! 감사합니다!

**Comment by HW-YUN** [comment]
> @vapury @Alegroha @HW-YUN v1.0.5 테스트 부탁드립니다~

업데이트 했는데, 그대로 입니다. 여전히 관리비항목 구성요소 1개만 나오네요

**Comment by HW-YUN** [comment]
> @vapury @Alegroha @HW-YUN v1.0.5 테스트 부탁드립니다~

해결 되었습니다. 감사합니다.
